site_name: SMapper
site_url: https://snt-arg.github.io/smapper_docs/
repo_url: https://github.com/snt-arg/smapper_docs
theme:
    logo: assets/logo.png
    favicon: assets/logo.png
    features:
        - content.code.copy
        - search.suggest
        - search.highlight
        - content.footnote.tooltips
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.footer

    icon:
        repo: fontawesome/brands/github
    name: material
    palette:
        # Dark Mode
        - scheme: slate
          primary: black
          accent: teal
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode

        # Light Mode
        - scheme: default
          primary: black
          accent: teal
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - md_in_html
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.blocks.caption
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator:
              !!python/name:material.extensions.emoji.to_svg # Page tree


nav:
    - Home:
          - SMapper: index.md
          - Publications: publications.md
    - About Device:
          - Platform:
                - Components: components/index.md
          - Software Stack:
                - Stack Overview: software_stack/index.md
    - Guides:
          - Initial Setup: guides/setup.md
          - Calibration: guides/calibration.md
          - Transferring Bags: guides/external_disk.md
          - JetPack Flashing: guides/jetpack.md
          - Networking: guides/networking.md

    - References:
          - SMapper API: software_stack/smapper_api.md
          - SMapper Web App: software_stack/smapper_app.md
          - SMapper Toolbox: software_stack/smapper_toolbox.md
          - Argus Camera ROS: software_stack/argus_cameras_ros.md

    - Datasets:
          - Datasets: datasets/index.md
